### ISSUE TITLE
Question regarding Training of the 

### ISSUE THREAD

**Issue by sandorkonya** [microsoft/UDOP#3]
Thank you for publishing UDOP, a real step towards unified document processing!

Can you give Information about the training time (on the used equipment) for the self-supervised learning and the curriculum learning parts?

thank you in advance!

**Comment by zinengtang** [comment]
We trained on our cluster with 32 A100.
It will take around 1 week for three curriculum stages.
Each stage takes 2-3 days.
Let me know if you have any questions

**Comment by sandorkonya** [comment]
Thank you!
