### ISSUE TITLE
Number of Epochs for Fine-tuning Tasks

### ISSUE THREAD

**Issue by srikar2097** [microsoft/UDOP#4]
Hi Authors @zinengtang,
Appreciate your interesting paper UDOP. Wanted to know the specifics on fine-tuning. Appendix C.6 in the paper does provide some details but the crucial detail of **number of epochs** is missing. Specifically:

1. Number of epochs fine-tuned for each downstream task?
2. Are all downstream tasks fine-tuned for the same number of epochs?

p.s. I posted this question in i-code repo too but that repo seems to be inactive.

**Comment by ziyi-yang** [comment]
It is answered here: https://github.com/microsoft/i-Code/issues/16
